site_name: Learn OpenTofu
site_url: https://www.patashale.in/learn-opentofu/
site_author: Patashale™
site_description: Learn everything about OpenTofu here at Patashale™.
theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: yellow
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: yellow
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.footer
    - navigation.tabs
    - content.tooltips
    - content.code.copy

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets:
     auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  generator: false
  social:
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@patashale
      name: Patashale™ on YouTube
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@patashale
      name: Patashale™ on Mastodon
    # - icon: fontawesome/brands/linkedin
    #   link: https://linkedin.com/company/patashale
    #   name: Patashale™ on LinkedIn
    # - icon: fontawesome/brands/gitlab
    #   link: https://gitlab.com/patashale
    #   name: Patashale™ on GitHub
    # - icon: fontawesome/brands/github
    #   link: https://github.com/patashale
    #   name: Patashale™ on GitHub
    - icon: fontawesome/brands/square-reddit
      link: https://reddit.com/r/patashale
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/patashale_in
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/patashale.bsky.social

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true
  - social:
      cards_layout_options:
        background_color: "#ffda18"

nav:
  - Home: index.md
  - Install: 
    - Overview: en/install/overview.md
    - MacOS: en/install/macos.md
    - Linux: en/install/linux.md
    - Windows: en/install/windows.md
  - Language:
    - Overview: en/language/overview.md
  - CLI: 
    - Overview: en/cli/overview.md
  - Internals:
    - Overview: en/internals/overview.md

copyright: Copyright &copy; 2023 <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://www.github.com/patashale">Patashale&#x2122;</a>. All rights reserved.

